/**
 * Пиксельные иконки: шаблоны 16×16, выводятся 32×32 (Scale2x + объём + контур).
 * Стоковые эмодзи в интерфейсе не используются — только эти иконки.
 */
import { hex, type RGBA } from './color';
import type { Bitmap } from './sprite';

const PAL: Record<string, string> = {
  Y: '#F2C040',
  y: '#B8802A',
  Z: '#FFE8A0',
  C: '#5AB8F0',
  c: '#2E6AB0',
  U: '#CFEFFF',
  R: '#E03A3A',
  r: '#8A1E2A',
  G: '#4FBF5A',
  g: '#2E7A34',
  P: '#9B4DE0',
  p: '#5A2A8A',
  W: '#F2E6D8',
  w: '#A89484',
  K: '#D8DEE8',
  k: '#8A92A6',
  B: '#9A6A3A',
  b: '#6A4424',
  O: '#F08A24',
  o: '#B85A14',
  S: '#F4D3B8',
  N: '#3A3E5A',
  M: '#E040FF',
  T: '#40E0D0',
  L: '#F2D46B',
  D: '#2A1E2E',
  X: '#1A1016',
  H: '#F26AA8',
  h: '#A8306A',
  Q: '#FFC4DE',
};

export const ICONS: Record<string, string[]> = {
  gold: [
    '................',
    '.....YYYYYY.....',
    '...YYZZZZZZYY...',
    '..YZZYYYYYYZZY..',
    '..YZYYYyyYYYZY..',
    '.YZYYYyYYyYYYZY.',
    '.YZYYYyYYYYYYZY.',
    '.YZYYYYyyYYYYyY.',
    '.YZYYYYYYyYYYyY.',
    '.YZYYYyYYyYYYyY.',
    '.YYYYYYyyYYYYyY.',
    '..YYYYYYYYYYyY..',
    '..YYyYYYYYYyyY..',
    '...YYyyyyyyYY...',
    '.....YYYYYY.....',
    '................',
  ],
  crystals: [
    '................',
    '......UUUU......',
    '....UUCCCCUU....',
    '...UCCUCCCCcU...',
    '..UCCUUCCCCCcU..',
    '..CCCCCCCCCCcc..',
    '..cCCCCCCCCccc..',
    '...cCCCCCCccc...',
    '....cCCCCccc....',
    '.....cCCccc.....',
    '......cCcc......',
    '.......cc.......',
    '................',
    '................',
    '................',
    '................',
  ],
  xp: [
    '................',
    '...WWWWWWWWWW...',
    '..WwPPPPPPPPWw..',
    '..WPPPPPPPPPPw..',
    '...WPZZZZZZPW...',
    '...WPPPPPPPPW...',
    '...WPZZZZZPPW...',
    '...WPPPPPPPPW...',
    '...WPZZZZZZPW...',
    '...WPPPPPPPPW...',
    '...WPZZZPPPPW...',
    '..WPPPPPPPPPPw..',
    '..WwPPPPPPPPWw..',
    '...WWWWWWWWWW...',
    '................',
    '................',
  ],
  scrolls: [
    '................',
    '..rRRRRRRRRRRr..',
    '..RWWWWWWWWWWR..',
    '...WwwwwwwwwW...',
    '...WWWWWWWWWW...',
    '...WwwwwwwwwW...',
    '...WWWWYYWWWW...',
    '...WWWYZZYWWW...',
    '...WWWYZZYWWW...',
    '...WWWWYYWWWW...',
    '...WwwwwwwwwW...',
    '...WWWWWWWWWW...',
    '..RWWWWWWWWWWR..',
    '..rRRRRRRRRRRr..',
    '................',
    '................',
  ],
  dust: [
    '................',
    '.......U........',
    '......UKU.......',
    '.......U....U...',
    '...U.......UKU..',
    '..UKU.......U...',
    '...U............',
    '......KKKK......',
    '....KKKKKKKK....',
    '...KkKKKKKKkK...',
    '..KKkkKKKKkkKK..',
    '..kkkkkkkkkkkk..',
    '...kkkkkkkkkk...',
    '................',
    '................',
    '................',
  ],
  starDust: [
    '................',
    '.......Y........',
    '.......Y........',
    '......YZY.......',
    '......YZY.......',
    '.YYYYYZZZYYYYY..',
    '..YZZZZZZZZZY...',
    '...YZZZZZZZY....',
    '....YZZZZZY.....',
    '....YZZYZZY.....',
    '...YZZY.YZZY....',
    '...YZY...YZY....',
    '..YY.......YY...',
    '................',
    '..U.........U...',
    '................',
  ],
  ether: [
    '................',
    '.....TTTTTT.....',
    '...TTUUUUUUTT...',
    '..TUUTTTTTTUUT..',
    '..TUTTPPPPTTUT..',
    '.TUTPPMMMMPPTUT.',
    '.TUTPMMUUMMPTUT.',
    '.TUTPMUUUUMPTUT.',
    '.TUTPMMUUMMPTUT.',
    '.TUTPPMMMMPPTUT.',
    '..TUTTPPPPTTUT..',
    '..TUUTTTTTTUUT..',
    '...TTUUUUUUTT...',
    '.....TTTTTT.....',
    '................',
    '................',
  ],
  arenaTokens: [
    '................',
    '..RR........RR..',
    '..rRR......RRr..',
    '...rRR....RRr...',
    '....rRRYYRRr....',
    '.....YYZZYY.....',
    '....YZZYYZZY....',
    '....YZYKKYZY....',
    '....YZKKKKZY....',
    '....YZYKKYZY....',
    '....YZZYYZZY....',
    '.....YYZZYY.....',
    '......YYYY......',
    '................',
    '................',
    '................',
  ],
  guildCoins: [
    '................',
    '.....yYYYYy.....',
    '...yYYZZZZYYy...',
    '..yYZZYYYYZZYy..',
    '..YZYCCCCCCYZY..',
    '.yZYCCUUUUCCYZy.',
    '.YZYCUCCCCUCYZY.',
    '.YZYCCCCCCCCYZY.',
    '.YZYyCCCCCCyYZY.',
    '.yZYYyCCCCyYYZy.',
    '..YZYYyCCyYYZY..',
    '..yYZZYyyYZZYy..',
    '...yYYZZZZYYy...',
    '.....yYYYYy.....',
    '................',
    '................',
  ],
  forgeMats: [
    '................',
    '................',
    '................',
    '....KKKKKKKK....',
    '...KUUUUUUUKk...',
    '..KUKKKKKKKKkk..',
    '.KKKKKKKKKKKkkk.',
    '.kkkkkkkkkkkkkk.',
    '.kKKKKKKKKKKKkk.',
    '.kkkkkkkkkkkkk..',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  divineMats: [
    '................',
    '.......M........',
    '......MUM.......',
    '.....RMUMY......',
    '....RRMUMYY.....',
    '...ORRMUMYYG....',
    '...OORMUMYGG....',
    '..OOORMUMYGGC...',
    '...OORMUMYGG....',
    '....ORMUMYG.....',
    '.....RMUMY......',
    '......MUM.......',
    '.......M........',
    '................',
    '................',
    '................',
  ],
  labCoins: [
    '................',
    '.....yYYYYy.....',
    '...yYYYYYYYYy...',
    '..yYbbbbbbbbYy..',
    '..YYbYYYYYYbYY..',
    '.yYYbYbbbbYbYYy.',
    '.YYYbYbYYbYbYYY.',
    '.YYYbYbYbbYbYYY.',
    '.YYYbYbYYYYbYYY.',
    '.yYYbYbbbbbbYYy.',
    '..YYbYYYYYYYYY..',
    '..yYbbbbbbbbYy..',
    '...yYYYYYYYYy...',
    '.....yYYYYy.....',
    '................',
    '................',
  ],
  eventTokens: [
    '................',
    '................',
    '..PPPPPPPPPPPP..',
    '..PMMMMMMMMMMP..',
    '..PM.MMMMMM.MP..',
    '...MMMZZMMMMM...',
    '...MMZZZZMMMM...',
    '...MMMZZMMMMM...',
    '..PM.MMMMMM.MP..',
    '..PMMMMMMMMMMP..',
    '..PPPPPPPPPPPP..',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  // ——— слоты ———
  weapon: [
    '................',
    '.............KK.',
    '............KUK.',
    '...........KUK..',
    '..........KUK...',
    '.........KUK....',
    '........KUK.....',
    '.......KUK......',
    '..y...KUK.......',
    '..yY.KUK........',
    '...yYUK.........',
    '....yY..........',
    '...bYyY.........',
    '..bb..yY........',
    '.bb.............',
    '................',
  ],
  offhand: [
    '................',
    '..KKKKKKKKKKKK..',
    '..KCCCCYYCCCCK..',
    '..KCCCCYYCCCCK..',
    '..KCCCCYYCCCCK..',
    '..KYYYYYYYYYYK..',
    '..KYYYYYYYYYYK..',
    '..KCCCCYYCCCCK..',
    '..KCCCCYYCCCCK..',
    '...KCCCYYCCCK...',
    '...KCCCYYCCCK...',
    '....KCCYYCCK....',
    '.....KCYYCK.....',
    '......KYYK......',
    '.......KK.......',
    '................',
  ],
  helmet: [
    '................',
    '.......YY.......',
    '.....KKKKKK.....',
    '....KUUKKKKK....',
    '...KUKKKKKKKk...',
    '...KUKKKKKKKk...',
    '..KKKKKKKKKKKk..',
    '..KKkkkkkkkkKk..',
    '..KKD.D..D.DKk..',
    '..KKkkkkkkkkKk..',
    '..KK........Kk..',
    '..Kk........kk..',
    '..kk........kk..',
    '................',
    '................',
    '................',
  ],
  armor: [
    '................',
    '..KKK......KKK..',
    '.KUKKK.KK.KKKKk.',
    '.KUKKKKKKKKKKKk.',
    '.KKKKKKYYKKKKKk.',
    '.kKKKKKYYKKKKkk.',
    '..kKKKKYYKKKKk..',
    '...KKKKKKKKKK...',
    '...KKKKKKKKKk...',
    '...YYYYYYYYYY...',
    '...KKKKKKKKKk...',
    '...KKKKKKKKKk...',
    '...kKKKKKKKkk...',
    '....kkkkkkkk....',
    '................',
    '................',
  ],
  gloves: [
    '................',
    '....B.B.B.......',
    '...BBBBBBB......',
    '...BBBBBBBB.....',
    '...BBBBBBBB.BB..',
    '...BBBBBBBBBBB..',
    '...BBBBBBBBBB...',
    '...BBBBBBBBB....',
    '...bBBBBBBBB....',
    '....bBBBBBB.....',
    '....YYYYYYY.....',
    '....bbbbbbb.....',
    '....bbbbbbb.....',
    '................',
    '................',
    '................',
  ],
  boots: [
    '................',
    '....BBBBBB......',
    '....BBBBBB......',
    '....YYYYYY......',
    '....BBBBBB......',
    '....BBBBBB......',
    '....BBBBBB......',
    '....BBBBBB......',
    '....BBBBBBBB....',
    '....BBBBBBBBBB..',
    '....BBBBBBBBBBB.',
    '....bbbbbbbbbbb.',
    '...bbbbbbbbbbbb.',
    '................',
    '................',
    '................',
  ],
  belt: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '.BBBBBYYYYBBBBB.',
    '.BBBBBY..YBBBBB.',
    '.bbbbbY..Ybbbbb.',
    '.bbbbbYYYYbbbbb.',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  cloak: [
    '................',
    '.....YYYYYY.....',
    '....RRRRRRRR....',
    '...RRRRRRRRRR...',
    '...RRRrRRrRRR...',
    '..RRRRrRRrRRRR..',
    '..RRRRrRRrRRRR..',
    '..RRRRrRRrRRRR..',
    '.RRRRRrRRrRRRRR.',
    '.RRRRRrRRrRRRRR.',
    '.RRRRRrRRrRRRRR.',
    '.rRRRRrRRrRRRRr.',
    '.rrRrrrRrrrRrrr.',
    '................',
    '................',
    '................',
  ],
  amulet: [
    '................',
    '...Y........Y...',
    '...Y........Y...',
    '....Y......Y....',
    '....Y......Y....',
    '.....Y....Y.....',
    '......YYYY......',
    '.....YRRRRY.....',
    '....YRRUURRY....',
    '....YRRURRRY....',
    '....YRRRRRRY....',
    '.....YRRRRY.....',
    '......YYYY......',
    '................',
    '................',
    '................',
  ],
  ring: [
    '................',
    '................',
    '......CCCC......',
    '.....CUUCCC.....',
    '......CCCC......',
    '.....YYYYYY.....',
    '....YY....YY....',
    '...YY......YY...',
    '...Y........Y...',
    '...Y........Y...',
    '...YY......YY...',
    '....YY....YY....',
    '.....YYYYYY.....',
    '................',
    '................',
    '................',
  ],
  // ——— навигация и интерфейс ———
  battle: [
    '................',
    '.KK..........KK.',
    '.KUK........KUK.',
    '..KUK......KUK..',
    '...KUK....KUK...',
    '....KUK..KUK....',
    '.....KUKKUK.....',
    '......KUUK......',
    '......KUUK......',
    '.....KUKKUK.....',
    '..y.KUK..KUK.y..',
    '..yyUK....KUyy..',
    '...yy......yy...',
    '..bbyy....yybb..',
    '.bb............b',
    '................',
  ],
  heroes: [
    '................',
    '.....RRRRRR.....',
    '....RRRRRRRR....',
    '...RRSSSSSSRR...',
    '...RSSSSSSSSR...',
    '...RSDSSSSDSR...',
    '...RSSSSSSSSR...',
    '...RRSSSMSSRR...',
    '...RR.SSSS.RR...',
    '...R.PPPPPP.R...',
    '....PPPYYPPP....',
    '...PPPPYYPPPP...',
    '...PPPPPPPPPP...',
    '...PPPPPPPPPP...',
    '................',
    '................',
  ],
  gear: [
    '................',
    '.....BBBBBB.....',
    '....B......B....',
    '...BBBBBBBBBB...',
    '..BBYYYYYYYYBB..',
    '..BYBBBBBBBBYB..',
    '..BYBBBYYBBBYB..',
    '..BYBBBYYBBBYB..',
    '..BYYYYYYYYYYB..',
    '..BYBBBBBBBBYB..',
    '..BYBBBBBBBBYB..',
    '..BYBBBBBBBBYB..',
    '..BBYYYYYYYYBB..',
    '...bbbbbbbbbb...',
    '................',
    '................',
  ],
  map: [
    '................',
    '..WWWWWWWWWWWW..',
    '.WwWWWWWWWWWWwW.',
    '.W.WGGWWWRWWW.W.',
    '.W.WGGGW.RWWW.W.',
    '.W.WGWW.WWWCW.W.',
    '.W.WWW.WWWCCW.W.',
    '.W.WW.WWWWCCW.W.',
    '.W.W.WWGGWWWW.W.',
    '.W.WRWWGGGWWW.W.',
    '.W.WWWWWGWWWW.W.',
    '.WwWWWWWWWWWWwW.',
    '..WWWWWWWWWWWW..',
    '................',
    '................',
    '................',
  ],
  hub: [
    '................',
    '..R.....R.....R.',
    '..RR....RR....RR',
    '..K.....K.....K.',
    '.KKK...KKK...KKK',
    '.KkK...KkK...KkK',
    '.KKKKKKKKKKKKKKK',
    '.KkKKKkKKKkKKKkK',
    '.KKKKKKKKKKKKKKK',
    '.KKKKKKbbbKKKKKK',
    '.KKKKKbbbbbKKKKK',
    '.KkKKKbbbbbKKkKK',
    '.KKKKKbbbbbKKKKK',
    '.kkkkkkkkkkkkkkk',
    '................',
    '................',
  ],
  plus: [
    '................',
    '................',
    '......GGGG......',
    '......GZZG......',
    '......GZZG......',
    '..GGGGGZZGGGGG..',
    '..GZZZZZZZZZZG..',
    '..GZZZZZZZZZZG..',
    '..GGGGGZZGGGGG..',
    '......GZZG......',
    '......GZZG......',
    '......GGGG......',
    '................',
    '................',
    '................',
    '................',
  ],
  settings: [
    '................',
    '.......KK.......',
    '...KK.KKKK.KK...',
    '...KKKKKKKKKK...',
    '....KKkkkkKK....',
    '..KKKk....kKKK..',
    '..KKk......kKK..',
    '...Kk......kK...',
    '..KKk......kKK..',
    '..KKKk....kKKK..',
    '....KKkkkkKK....',
    '...KKKKKKKKKK...',
    '...KK.KKKK.KK...',
    '.......KK.......',
    '................',
    '................',
  ],
  close: [
    '................',
    '................',
    '..RR........RR..',
    '..RRR......RRR..',
    '...RRR....RRR...',
    '....RRR..RRR....',
    '.....RRRRRR.....',
    '......RRRR......',
    '......RRRR......',
    '.....RRRRRR.....',
    '....RRR..RRR....',
    '...RRR....RRR...',
    '..RRR......RRR..',
    '..RR........RR..',
    '................',
    '................',
  ],
  lock: [
    '................',
    '......KKKK......',
    '.....KK..KK.....',
    '....KK....KK....',
    '....K......K....',
    '....K......K....',
    '...YYYYYYYYYY...',
    '...YZZZZZZZZY...',
    '...YZYYbbYYZY...',
    '...YZYYbbYYZY...',
    '...YZYYYbYYZY...',
    '...YZYYYbYYZY...',
    '...YZZZZZZZZY...',
    '...yyyyyyyyyy...',
    '................',
    '................',
  ],
  star: [
    '................',
    '.......YY.......',
    '.......YY.......',
    '......YZZY......',
    '......YZZY......',
    '.YYYYYZZZZYYYYY.',
    '..YZZZZZZZZZZY..',
    '...YZZZZZZZZY...',
    '....YZZZZZZY....',
    '....YZZYYZZY....',
    '...YZZY..YZZY...',
    '...YZY....YZY...',
    '..YY........YY..',
    '................',
    '................',
    '................',
  ],
  chest: [
    '................',
    '................',
    '...BBBBBBBBBB...',
    '..BYYYYYYYYYYB..',
    '..BYBBBBBBBBYB..',
    '..BYBBBBBBBBYB..',
    '..YYYYYYYYYYYY..',
    '..BBBBBYYBBBBB..',
    '..BYBBYZZYBBYB..',
    '..BYBBBYYBBBYB..',
    '..BYBBBBBBBBYB..',
    '..BYBBBBBBBBYB..',
    '..BYYYYYYYYYYB..',
    '..bbbbbbbbbbbb..',
    '................',
    '................',
  ],
  chestOpen: [
    '................',
    '...BBBBBBBBBB...',
    '..BYYYYYYYYYYB..',
    '..BYBBBBBBBBYB..',
    '..BYYYYYYYYYYB..',
    '..Z.Y.Z..Y.Z....',
    '..YZYYZYYZYYZY..',
    '..BYZYYZZYYZYB..',
    '..BYBBYZZYBBYB..',
    '..BYBBBYYBBBYB..',
    '..BYBBBBBBBBYB..',
    '..BYBBBBBBBBYB..',
    '..BYYYYYYYYYYB..',
    '..bbbbbbbbbbbb..',
    '................',
    '................',
  ],
  skull: [
    '................',
    '....WWWWWWWW....',
    '...WWWWWWWWWW...',
    '..WWWWWWWWWWWW..',
    '..WWWWWWWWWWWW..',
    '..WWDDDWWDDDWW..',
    '..WWDRDWWDRDWW..',
    '..WWDDDWWDDDWW..',
    '..WWWWWDDWWWWW..',
    '...WWWWDDWWWW...',
    '....WWWWWWWW....',
    '....WDWDWDWW....',
    '....WWWWWWWW....',
    '.....wwwwww.....',
    '................',
    '................',
  ],
  speed: [
    '................',
    '................',
    '..Y.....Y.......',
    '..YY....YY......',
    '..YZY...YZY.....',
    '..YZZY..YZZY....',
    '..YZZZY.YZZZY...',
    '..YZZZZYYZZZZY..',
    '..YZZZY.YZZZY...',
    '..YZZY..YZZY....',
    '..YZY...YZY.....',
    '..YY....YY......',
    '..Y.....Y.......',
    '................',
    '................',
    '................',
  ],
  mail: [
    '................',
    '................',
    '................',
    '.WWWWWWWWWWWWWW.',
    '.WwWWWWWWWWWWwW.',
    '.WWwWWWWWWWWwWW.',
    '.WWWwWWWWWWwWWW.',
    '.WWWWwWRRWwWWWW.',
    '.WWWWWwRRwWWWWW.',
    '.WWWWwWWWWwWWWW.',
    '.WWWwWWWWWWwWWW.',
    '.WWwWWWWWWWWwWW.',
    '.WWWWWWWWWWWWWW.',
    '................',
    '................',
    '................',
  ],
  quest: [
    '................',
    '..WWWWWWWWWWW...',
    '..WwwwwwwwwwWW..',
    '..WWWWWWWWWWWW..',
    '..WG.WwwwwwwWW..',
    '..WGGWWWWWWWWW..',
    '..WWGWwwwwwwWW..',
    '..WWWWWWWWWWWW..',
    '..WG.WwwwwwwWW..',
    '..WGGWWWWWWWWW..',
    '..WWGWwwwwwwWW..',
    '..WWWWWWWWWWWW..',
    '..WWWWWWWWWWW...',
    '................',
    '................',
    '................',
  ],
  shop: [
    '................',
    '.....bbbbbb.....',
    '....b......b....',
    '....b......b....',
    '..BBBBBBBBBBBB..',
    '..BYYYYYYYYYYB..',
    '..BBBBBBBBBBBB..',
    '..BBBBBYYBBBBB..',
    '..BBBBYZZYBBBB..',
    '..BBBBBYYBBBBB..',
    '..BBBBBBBBBBBB..',
    '..BBBBBBBBBBBB..',
    '..bbbbbbbbbbbb..',
    '................',
    '................',
    '................',
  ],
  summon: [
    '................',
    '.....PPPPPP.....',
    '...PPMMMMMMPP...',
    '..PMMUUMMMMMMP..',
    '..PMUUMMMMMMMP..',
    '.PMMUMMMMMMMMMP.',
    '.PMMMMMZZMMMMMP.',
    '.PMMMMZZZZMMMMP.',
    '.PMMMMMZZMMMMMP.',
    '..PMMMMMMMMMMP..',
    '..PPMMMMMMMMPP..',
    '....PPPPPPPP....',
    '...YYYYYYYYYY...',
    '..yyyyyyyyyyyy..',
    '................',
    '................',
  ],
  pass: [
    '................',
    '................',
    '..YYYYYYYYYYYY..',
    '..YRRRRRRRRRRY..',
    '..YR.RRRRRR.RY..',
    '..YRRRRZZRRRRY..',
    '..YRRRZZZZRRRY..',
    '..YRRRRZZRRRRY..',
    '..YR.RRRRRR.RY..',
    '..YRRRRRRRRRRY..',
    '..YYYYYYYYYYYY..',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  trophy: [
    '................',
    '..YYYYYYYYYYYY..',
    '.YYZZZZZZZZZYYY.',
    '.Y.YZZZZZZZY..Y.',
    '.Y.YZZZZZZZY..Y.',
    '..YYZZZZZZZYYY..',
    '....YZZZZZY.....',
    '.....YZZZY......',
    '......YZY.......',
    '......YYY.......',
    '.....YYYYY......',
    '....bbbbbbb.....',
    '....bbbbbbb.....',
    '................',
    '................',
    '................',
  ],
  constellation: [
    '................',
    '..Y.............',
    '.YZY........U...',
    '..Y.U......UKU..',
    '.....U......U...',
    '......Y.....U...',
    '.....YZY...U....',
    '......Y...U.....',
    '.......U.U......',
    '........Y.......',
    '.......YZY......',
    '........Y.......',
    '....U...U.......',
    '...UKU...U..Y...',
    '....U.....UYZY..',
    '............Y...',
  ],
  ascension: [
    '................',
    '.......TT.......',
    '......TUUT......',
    '.....TUUUUT.....',
    '....TUUTTUUT....',
    '...TUUT..TUUT...',
    '..TUUT.TT.TUUT..',
    '.....TTUUTT.....',
    '....TUUTTUUT....',
    '...TUUT..TUUT...',
    '..TUUT....TUUT..',
    '..TT........TT..',
    '................',
    '................',
    '................',
    '................',
  ],
  tower: [
    '................',
    '....K.K..K.K....',
    '....KKKKKKKK....',
    '.....KkKKkK.....',
    '.....KKKKKK.....',
    '.....KKYYKK.....',
    '.....KKYYKK.....',
    '.....KkKKkK.....',
    '....KKKKKKKK....',
    '....KKKKKKKK....',
    '....KkKbbKkK....',
    '....KKbbbbKK....',
    '...KKKbbbbKKK...',
    '...kkkkkkkkkk...',
    '................',
    '................',
  ],
  dungeon: [
    '................',
    '.....kkkkkk.....',
    '...kkKKKKKKkk...',
    '..kKKKKKKKKKKk..',
    '..kKKDDDDDDKKk..',
    '.kKKDDDDDDDDKKk.',
    '.kKKDDRDDRDDKKk.',
    '.kKKDDDDDDDDKKk.',
    '.kKKDDDDDDDDKKk.',
    '.kKKDDDDDDDDKKk.',
    '.kKKDDDDDDDDKKk.',
    '.kKKDDDDDDDDKKk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
  ],
  expedition: [
    '................',
    '...b............',
    '...bRRRRRR......',
    '...bRRRRRRRR....',
    '...bRRYYRRRRRR..',
    '...bRRRRRRRR....',
    '...bRRRRRR......',
    '...b............',
    '...b............',
    '...b............',
    '...b............',
    '..GGGG..........',
    '.GGGGGGGGGG.....',
    'GGgGGGGgGGGGGG..',
    '................',
    '................',
  ],
  labyrinth: [
    '................',
    '.KKKKKKKKKKKKKK.',
    '.K......K.....K.',
    '.K.KKKK.K.KKK.K.',
    '.K.K....K...K.K.',
    '.K.K.KKKKKK.K.K.',
    '.K.K.K....K.K.K.',
    '.K.K.K.YY.K...K.',
    '.K...K.YY.KKKKK.',
    '.KKKKK....K...K.',
    '.K.....KKKK.K.K.',
    '.K.KKKKK....K.K.',
    '.K.......KK.K...',
    '.KKKKKKKKKKKKKK.',
    '................',
    '................',
  ],
  arena: [
    '................',
    '..G..........G..',
    '.GG..........GG.',
    '.G..KK....KK..G.',
    'GG..KUK..KUK..GG',
    'G....KUKKUK....G',
    'G.....KUUK.....G',
    'GG....KUUK....GG',
    '.G...KUKKUK...G.',
    '.GG.yUK..KUy.GG.',
    '..GGyy....yyGG..',
    '...GGGG..GGGG...',
    '................',
    '................',
    '................',
    '................',
  ],
  abyss: [
    '................',
    '.....pppppp.....',
    '...ppPPPPPPpp...',
    '..pPPppppppPPp..',
    '..pPpPPPPPPpPp..',
    '.pPpPppppppPpPp.',
    '.pPpPpMMMMpPpPp.',
    '.pPpPpMDDMpPpPp.',
    '.pPpPpMDDMpPpPp.',
    '.pPpPppMMppPpPp.',
    '..pPpPPPPPPpPp..',
    '..pPPppppppPPp..',
    '...ppPPPPPPpp...',
    '.....pppppp.....',
    '................',
    '................',
  ],
  // Разлом Колосса: трещина в небе с багровым глазом
  rift: [
    '................',
    '.......pp.......',
    '......pMMp......',
    '.....pMRRMp.....',
    '....pMRZZRMp....',
    '...pMRZDDZRMp...',
    '...pMRZDDZRMp...',
    '....pMRZZRMp....',
    '.....pMRRMp.....',
    '......pMMp......',
    '.......pp.......',
    '.....p.pp.p.....',
    '....p..pp..p....',
    '...p...pp...p...',
    '..p....pp....p..',
    '................',
  ],
  // Стихийные шпили: пять кристаллов стихий
  spire: [
    '.......Z........',
    '......ZYZ.......',
    '..R...YYY...C...',
    '.RRR..YYY..CCC..',
    '.RrR..YyY..CcC..',
    '.RrR.GYyYP.CcC..',
    '.RrRGGGyPPPCcC..',
    '.RrRGgGyPpPCcC..',
    '.RrRGgGyPpPCcC..',
    '.kRkGgGkPpPkCk..',
    '.kkkGgGkPpPkkk..',
    '.kkkkkkkkkkkkk..',
    '.KKKKKKKKKKKKK..',
    '.kkkkkkkkkkkkk..',
    '................',
    '................',
  ],
  // Нашествие: скрещённые клинки над волной черепов
  horde: [
    '................',
    '.K............K.',
    '..K..........K..',
    '...K........K...',
    '....K......K....',
    '.....K....K.....',
    '......KyyK......',
    '......yKKy......',
    '.....K....K.....',
    '...WW..WW..WW...',
    '..WDDWWDDWWDDW..',
    '..WWWWWWWWWWWW..',
    '..WDWDWDWDWDWW..',
    '...wWwWwWwWww...',
    '................',
    '................',
  ],
  dev: [
    '................',
    '..........KKK...',
    '.........KK.KK..',
    '.........K...K..',
    '........KK..KK..',
    '.......KKKKKK...',
    '......KKK.......',
    '.....KKK........',
    '....KKK.........',
    '...KKK..........',
    '..OOK...........',
    '.OOO............',
    '.OO.............',
    '................',
    '................',
    '................',
  ],
  forge: [
    '................',
    '................',
    '................',
    '..kkkkkkkkkkk...',
    '.kKKKKKKKKKKKKk.',
    '..kKKKKKKKKKKk..',
    '....kKKKKKKk....',
    '.....kKKKKk.....',
    '......kKKk......',
    '......kKKk......',
    '....kkKKKKkk....',
    '...kKKKKKKKKk...',
    '...kkkkkkkkkk...',
    '................',
    '................',
    '................',
  ],
  gem: [
    '................',
    '................',
    '.....RRRRRR.....',
    '....RZZRRRRR....',
    '...RZRRRRRRrR...',
    '..RRRRRRRRRRrR..',
    '..rRRRRRRRRrrr..',
    '...rRRRRRRrrr...',
    '....rRRRRrrr....',
    '.....rRRrrr.....',
    '......rRrr......',
    '.......rr.......',
    '................',
    '................',
    '................',
    '................',
  ],
  hearts: [
    '................',
    '................',
    '...hhh....hhh...',
    '..hHHHh..hHHHh..',
    '.hHQQHHhhHHHHHh.',
    '.hHQHHHHHHHHHHh.',
    '.hHHHHHHHHHHHHh.',
    '.hHHHHHHHHHHHHh.',
    '..hHHHHHHHHHHh..',
    '...hHHHHHHHHh...',
    '....hHHHHHHh....',
    '.....hHHHHh.....',
    '......hHHh......',
    '.......hh.......',
    '................',
    '................',
  ],
  care: [
    '................',
    '..Z.............',
    '.ZZZ..hhh.hhh...',
    '..Z..hHHHhHHHh..',
    '.....hHQHHHHHh..',
    '.....hHHHHHHHh..',
    '......hHHHHHh...',
    '.......hHHHh....',
    '..WWWW..hHh.....',
    '.WWWWWW..h......',
    '.WSSSSW.........',
    '.WSSSSWWWWWW....',
    '..WWWWWWWWWWW...',
    '...wwwwwwwww.Z..',
    '............ZZZ.',
    '.............Z..',
  ],
  news: [
    '................',
    '...WWWWWWWWWW...',
    '..WwWWWWWWWWwW..',
    '..WWWWWWWWWWWW..',
    '..WWRRRRRRRRWW..',
    '..WWWWWWWWWWWW..',
    '..WWwwwwwwwwWW..',
    '..WWWWWWWWWWWW..',
    '..WWwwwwwwwWWW..',
    '..WWWWWWWWWWWW..',
    '..WWwwwwwwwwWW..',
    '..WWWWWWWWWWWW..',
    '..WWwwwwwWWYYW..',
    '..WWWWWWWWYZZY..',
    '...WWWWWWWWYYY..',
    '................',
  ],
  gift: [
    '................',
    '....RR....RR....',
    '...R..R..R..R...',
    '....RRRRRRRR....',
    '..GGGGGRRGGGGG..',
    '..GZZZZRRZZZZG..',
    '..GGGGGRRGGGGG..',
    '...GGGGRRGGGG...',
    '...GGGGRRGGGG...',
    '...GGGGRRGGGG...',
    '...GGGGRRGGGG...',
    '...GGGGRRGGGG...',
    '...gggggggggg...',
    '................',
    '................',
    '................',
  ],
  back: [
    '................',
    '................',
    '......Y.........',
    '.....YY.........',
    '....YZY.........',
    '...YZZYYYYYYYY..',
    '..YZZZZZZZZZZY..',
    '..YZZZZZZZZZZY..',
    '...YZZYYYYYYYY..',
    '....YZY.........',
    '.....YY.........',
    '......Y.........',
    '................',
    '................',
    '................',
    '................',
  ],
  up: [
    '................',
    '.......G........',
    '......GGG.......',
    '.....GGGGG......',
    '....GGGGGGG.....',
    '...GGGGGGGGG....',
    '......GGG.......',
    '......GGG.......',
    '......GGG.......',
    '......GGG.......',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  down: [
    '................',
    '......RRR.......',
    '......RRR.......',
    '......RRR.......',
    '......RRR.......',
    '...RRRRRRRRR....',
    '....RRRRRRR.....',
    '.....RRRRR......',
    '......RRR.......',
    '.......R........',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  check: [
    '................',
    '................',
    '.............G..',
    '............GG..',
    '...........GG...',
    '..........GG....',
    '..G......GG.....',
    '..GG....GG......',
    '...GG..GG.......',
    '....GGGG........',
    '.....GG.........',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  sound: [
    '................',
    '......K.........',
    '.....KK...Y.....',
    '....KKK....Y....',
    '.KKKKKK..Y..Y...',
    '.KKKKKK...Y.Y...',
    '.KKKKKK...Y.Y...',
    '.KKKKKK..Y..Y...',
    '....KKK....Y....',
    '.....KK...Y.....',
    '......K.........',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  info: [
    '................',
    '.....CCCCCC.....',
    '...CCCCCCCCCC...',
    '..CCCCCUUCCCCC..',
    '..CCCCCUUCCCCC..',
    '.CCCCCCCCCCCCCC.',
    '.CCCCCUUUCCCCCC.',
    '.CCCCCCUUCCCCCC.',
    '.CCCCCCUUCCCCCC.',
    '.CCCCCCUUCCCCCC.',
    '..CCCCUUUUCCCC..',
    '..CCCCCCCCCCCC..',
    '...CCCCCCCCCC...',
    '.....CCCCCC.....',
    '................',
    '................',
  ],
  // ——— стихии ———
  fire: [
    '................',
    '.......R........',
    '......RR........',
    '......ROR.......',
    '.....ROOR...R...',
    '....ROOOR..RR...',
    '...ROOYOOR.RR...',
    '...ROYYYOORR....',
    '..ROOYZYYOOR....',
    '..ROYZZZYYOR....',
    '..ROYZZZZYOR....',
    '..ROYYZZYYOR....',
    '...ROOYYOOR.....',
    '....RRRRRR......',
    '................',
    '................',
  ],
  nature: [
    '................',
    '..........GGG...',
    '........GGGGG...',
    '......GGGZGGG...',
    '.....GGGZGGGG...',
    '....GGGZGGGGg...',
    '....GGZGGGGgg...',
    '...GGZGGGGgg....',
    '...GZGGGGgg.....',
    '...ZGGGggg......',
    '..Z.gggg........',
    '.Z..............',
    'Z...............',
    '................',
    '................',
    '................',
  ],
  water: [
    '................',
    '.......C........',
    '.......C........',
    '......CCC.......',
    '......CCC.......',
    '.....CCCCC......',
    '....CCCCCCC.....',
    '....CUCCCCC.....',
    '...CCUCCCCCc....',
    '...CCUUCCCCc....',
    '...CCCCCCCCc....',
    '....CCCCCCc.....',
    '.....cccccc.....',
    '................',
    '................',
    '................',
  ],
  light: [
    '................',
    '.......L........',
    '..L....L....L...',
    '...L...L...L....',
    '.....LLLLL......',
    '....LZZZZZL.....',
    '....LZZZZZL.....',
    'LLLLLZZZZZLLLLL.',
    '....LZZZZZL.....',
    '....LZZZZZL.....',
    '.....LLLLL......',
    '...L...L...L....',
    '..L....L....L...',
    '.......L........',
    '................',
    '................',
  ],
  dark: [
    '................',
    '......PPPP......',
    '....PPPPP.......',
    '...PPPPP........',
    '..PPPPP.........',
    '..PPPP.......M..',
    '.PPPPP..........',
    '.PPPPP..........',
    '.PPPPP.......M..',
    '.PPPPPP.........',
    '..PPPPPP......P.',
    '..PPPPPPPP..PP..',
    '...PPPPPPPPPP...',
    '.....PPPPPP.....',
    '................',
    '................',
  ],
};

// классы — переиспользуем подходящие иконки
ICONS.guardian = ICONS.offhand;
ICONS.berserker = [
  '................',
  '......KKKK......',
  '....KKKKKKK.....',
  '...KKUUKKKKK....',
  '...KUKKKKKKkb...',
  '...KKKKKKKkbb...',
  '....KKKKKkbb....',
  '......kkbbb.....',
  '.......bbb......',
  '......bbb.......',
  '.....bbb........',
  '....bbb.........',
  '...bbb..........',
  '..bbb...........',
  '................',
  '................',
];
ICONS.archer = [
  '................',
  '.....BB.........',
  '....B..BW.......',
  '...B....W.......',
  '..B.....W.......',
  '..B.....W..KK...',
  '.B......WKKKUK..',
  '.B......W...KK..',
  '.B......W.......',
  '..B.....W.......',
  '..B.....W.......',
  '...B....W.......',
  '....B..BW.......',
  '.....BB.........',
  '................',
  '................',
];
ICONS.sorceress = [
  '................',
  '.......P........',
  '......PPP.......',
  '.....PPYPP......',
  '....PPPPPPP.....',
  '....PPPPPPP.....',
  '...PPPPPPPPP....',
  '.YYYYYYYYYYYYY..',
  '..pppppppppppp..',
  '................',
  '....C...........',
  '...CUC..........',
  '....C...........',
  '................',
  '................',
  '................',
];
ICONS.priestess = [
  '................',
  '......YYYY......',
  '.....YZZZZY.....',
  '......YYYY......',
  '.......YY.......',
  '....YYYYYYYY....',
  '....YZZZZZZY....',
  '....YYYYYYYY....',
  '.......YY.......',
  '.......YY.......',
  '.......YY.......',
  '.......YY.......',
  '.......YY.......',
  '.......yy.......',
  '................',
  '................',
];
ICONS.necromancer = ICONS.skull;
ICONS.assassin = [
  '................',
  '..K.........K...',
  '..KK.......KK...',
  '...KK.....KK....',
  '....KU...UK.....',
  '.....KU.UK......',
  '......KUK.......',
  '.....yKUKy......',
  '....yy...yy.....',
  '...bb.....bb....',
  '..bb.......bb...',
  '................',
  '................',
  '................',
  '................',
  '................',
];
ICONS.bard = [
  '................',
  '...........YYY..',
  '..........YY....',
  '.........YY.....',
  '........BY......',
  '...BBBBBB.......',
  '..BBBBBBBB......',
  '.BBBbbbBBB......',
  '.BBbWWWbBB......',
  '.BBbWWWbBB......',
  '.BBBbbbBBB......',
  '..BBBBBBBB......',
  '...BBBBBB.......',
  '................',
  '................',
  '................',
];
ICONS.hero = ICONS.heroes;

const OUTLINE = hex(PAL.X);

/** Растеризовать иконку в RGBA 16×16 с автоконтуром. */
/** Scale2x (EPX): удваивает разрешение, сглаживая диагонали без размытия. */
function scale2x(src: string[], w: number, h: number): string[] {
  const at = (x: number, y: number) => (x < 0 || y < 0 || x >= w || y >= h ? '.' : src[y * w + x]);
  const out = new Array<string>(w * 2 * h * 2);
  for (let y = 0; y < h; y++)
    for (let x = 0; x < w; x++) {
      const P = at(x, y);
      const A = at(x, y - 1);
      const B = at(x + 1, y);
      const C = at(x - 1, y);
      const D = at(x, y + 1);
      const W2 = w * 2;
      out[y * 2 * W2 + x * 2] = C === A && C !== D && A !== B ? A : P;
      out[y * 2 * W2 + x * 2 + 1] = A === B && A !== C && B !== D ? B : P;
      out[(y * 2 + 1) * W2 + x * 2] = D === C && D !== B && C !== A ? C : P;
      out[(y * 2 + 1) * W2 + x * 2 + 1] = B === D && B !== A && D !== C ? D : P;
    }
  return out;
}

function shade(c: RGBA, k: number): RGBA {
  const f = (v: number) => Math.max(0, Math.min(255, Math.round(k > 0 ? v + (255 - v) * k : v * (1 + k))));
  return [f(c[0]), f(c[1]), f(c[2]), c[3]];
}

/**
 * Иконка 32×32: шаблон 16×16 увеличивается Scale2x, затем объём (блик сверху-слева,
 * тень снизу-справа по краю силуэта) и тонкий тёмный контур.
 */
export function renderIcon(name: string): Bitmap {
  const rows = ICONS[name] ?? ICONS.info;
  const sw = 16;
  const sh = 16;
  const src: string[] = [];
  for (let y = 0; y < sh; y++) for (let x = 0; x < sw; x++) src.push(rows[y]?.[x] && rows[y][x] !== ' ' ? rows[y][x] : '.');
  const w = sw * 2;
  const h = sh * 2;
  const g = scale2x(src, sw, sh);
  const solid = (x: number, y: number) => x >= 0 && y >= 0 && x < w && y < h && g[y * w + x] !== '.';
  const data = new Uint8ClampedArray(w * h * 4);
  for (let y = 0; y < h; y++)
    for (let x = 0; x < w; x++) {
      const i = y * w + x;
      const ch = g[i];
      if (ch === '.') {
        if (solid(x - 1, y) || solid(x + 1, y) || solid(x, y - 1) || solid(x, y + 1)) data.set(OUTLINE, i * 4);
        continue;
      }
      let col = hex(PAL[ch] ?? '#FF00FF');
      if (ch !== 'X' && ch !== 'D') {
        if (!solid(x + 1, y) || !solid(x, y + 1)) col = shade(col, -0.22);
        else if (!solid(x - 1, y) || !solid(x, y - 1)) col = shade(col, 0.22);
      }
      data.set(col, i * 4);
    }
  return { w, h, data };
}

export const ICON_NAMES = Object.keys(ICONS);
